//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD_Crud_Fashion.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class OrderEntry
    {
        [Key]
        public int Id { get; set; }
        public int CustomersId { get; set; }

        [ForeignKey("CustomersId")]
        public virtual Customer Customer { get; set; }

        public int ProductsId { get; set; }

        [ForeignKey("ProductsId")]
        public virtual Product Product { get; set; }


    }
}
