//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD_Crud_Fashion.Models

{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;



    public partial class Product
    {

        [Key]
        public int ProductsId { get; set; }
        [Display(Name = "Products Name "), Required]
        public string ProductsName { get; set; }


        public virtual ICollection<OrderEntry> OrderEntries { get; set; }
    }
}
